### ISSUE TITLE
Get the password and continue

### ISSUE THREAD

**Issue by enomothem** [evilsocket/legba#13]
Get the password and continue

- rustc 1.73.0 (cc66ad468 2023-10-03)
- cargo 1.73.0 (9c4383fb5 2023-08-26)
- Windows10

![image](https://github.com/evilsocket/legba/assets/45089051/6fe3c899-fe73-414a-9a82-69572cd5a790)

`.\legba.exe mysql --username root --password .\password.txt --target localhost:3306`

password.txt  10000words

**Comment by evilsocket** [comment]
@enomothem I'm not sure what are you asking for here, could you elaborate more? Even in your own language will be ok, I'll translate :D

**Comment by evilsocket** [comment]
you can make it stop at the first positive find with --single-match

**Comment by enomothem** [comment]
好的，我懂你的意思了，得到答案并不会停止，需要使用`--single-match`才能在第一个发现处停止。

是的，我是这个意思，我想在发现后立即停止。

**Comment by enomothem** [comment]
@evilsocket bro，我正在学习rust，在legba中学习到了很多，有没有一些学习rust的心得🙂

**Comment by evilsocket** [comment]
@enomothem honestly, just have patience XD Rust can be a bitch sometimes, the borrow checker can be your worst enemy but also your best friend :D

**Comment by enomothem** [comment]
@evilsocket 是的，官方的教程太难了，我无从下手

**Comment by evilsocket** [comment]
@enomothem yeah i feel you, i feel lost with the official documentation/tutorials too XD

there's this book that's pretty great to start because it doesn't focus too much on the borrow checker -> https://www.manning.com/books/rust-in-action

then when you got the basics down and maybe wrote a few things, you can go deeper in rabbit hole with this one -> https://www.packtpub.com/product/hands-on-concurrency-with-rust/9781788399975

they're both very practical, hope that helps

**Comment by enomothem** [comment]
@evilsocket  Thank you for sharing. Thank you

**Comment by enomothem** [comment]
是的，我买了纸质版的这本书，非常棒
https://www.manning.com/books/rust-in-action
